version = 0.1

[default.deploy.parameters]
stack_name = "RiftScribe-Backend"
resolve_s3 = true
s3_prefix = "RiftScribe-Backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-central-1"

[default.build.parameters]
runtime = "nodejs18.x"
cached = true
parallel = true
