version = 0.1

[default.deploy.parameters]
stack_name = "RiftScribe-backend"
resolve_s3 = true
s3_prefix = "RiftScribe-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ForceRedeploy=\"true\""
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
